id: P009194
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:27:27.170857
source_metadata:
  id: bdr:W2CZ7913
  title: འཇམ་དབྱངས་མཁྱེན་བརྩེའི་དབང་ཕྱུག་གི་རྣམ་ཐར་
  author: ''
  volumes:
    cdfbd809129c456ba69d81fd346b4354:
      image_group_id: I1KG3424
      title: ''
      volume_number: 1
      total_pages: 232
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
